---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu1204
    driver:
      box: hashicorp/precise64

suites:
  - name: default
    run_list:
      - recipe[motd::default]
    attributes:
