name 'apache'
maintainer 'Artem Ervits'
maintainer_email 'dbist13@gmail.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.1.0'
